     <table>
        <tr>
            <th>Player</th>
            <th>Transaction</th>
            <th>Quantity</th>
            <th>DateTime</th>
         </tr>
        {transactions}
            <tr>
                <td>{Player}</td>
                <td>{Trans}</td>
                <td>{Quantity}</td>
                <td>{DateTime}</td>
            </tr>
        {/transactions}
     </table>